### ISSUE TITLE
[Bug] The default case in aws-lite-performance throws "ignored.includes is not a function"

### ISSUE THREAD

**Issue by platienum** [architect/aws-lite#54]
## Describe the bug

Refer https://github.com/architect/aws-lite-performance/issues/3

## Steps to reproduce

Refer the default case in `aws-lite-performance`

#### Observed behavior

An error `ignored.includes is not a function` is thrown.

#### Expected behavior

Error not thrown, and the API call executes successfully.

**Comment by platienum** [comment]
Possibly caused by https://github.com/architect/aws-lite/commit/6421e88f295fddd2bd8eb89c63db851aa2278ebf

cc @ryanblock

**Comment by ryanblock** [comment]
Definitely caused by that change. :)

Thanks, @platienum!
